# Generated by Django 4.2.4 on 2023-09-05 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_organization_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='members',
        ),
    ]
