# Generated by Django 4.2.4 on 2023-09-08 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_remove_team_members_alter_team_created_by'),
        ('client', '0005_client_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='team.team'),
        ),
    ]
