# Generated by Django 4.2.4 on 2023-10-23 11:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_alter_client_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.CharField(max_length=254, validators=[django.core.validators.EmailValidator(message='The email address is not valid! Please enter a valid email address!')]),
        ),
    ]
