# Generated by Django 4.2.4 on 2023-09-04 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0002_rename_modified_at_lead_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='converted',
            field=models.BooleanField(default=False),
        ),
    ]
