# Generated by Django 4.2.4 on 2023-10-23 11:23

import apps.lead.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0009_alter_lead_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='name',
            field=models.CharField(max_length=50, validators=[apps.lead.validators.name_validator]),
        ),
    ]
