# Generated by Django 4.2.4 on 2023-10-23 11:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0010_alter_lead_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='Please enter a valid email address')]),
        ),
    ]
