# Generated by Django 4.2.4 on 2023-10-23 11:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_contactmodel_options_contactmodel_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='email',
            field=models.CharField(max_length=50, validators=[django.core.validators.EmailValidator(message='The email address is not valid! Please try again!')]),
        ),
    ]
