# Generated by Django 4.2.4 on 2023-09-06 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_org_owner',
            field=models.BooleanField(default=False),
        ),
    ]
