# Generated by Django 4.2.4 on 2023-09-07 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_remove_team_members_alter_team_created_by'),
        ('account', '0007_user_is_org_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='team.team'),
            preserve_default=False,
        ),
    ]
