# Generated by Django 4.2.4 on 2023-09-07 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_user_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='organization',
        ),
    ]
